import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:go_router/go_router.dart';

import '../../../../core/theme/app_colors.dart';
import '../../providers/employee_providers.dart';

class RegistrationLinksDialog extends ConsumerWidget {
  const RegistrationLinksDialog({super.key});

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final linksAsync = ref.watch(registrationLinksProvider);

    final screenWidth = MediaQuery.of(context).size.width;

    return AlertDialog(
      insetPadding: const EdgeInsets.symmetric(horizontal: 16, vertical: 24),
      title: Row(
        children: [
          const Icon(Icons.link_outlined, color: AppColors.active),
          const SizedBox(width: 8),
          const Expanded(
            child: Text(
              'Registration Links Status',
              maxLines: 2,
              overflow: TextOverflow.ellipsis,
              style: TextStyle(fontSize: 16, fontWeight: FontWeight.bold),
            ),
          ),
          IconButton(
            icon: const Icon(Icons.close, size: 20),
            onPressed: () => Navigator.of(context).pop(),
          ),
        ],
      ),
      content: SizedBox(
        width: screenWidth < 860 ? screenWidth * 0.9 : 820,
        height: 480,
        child: linksAsync.when(
          loading: () => const Center(child: CircularProgressIndicator()),
          error: (err, _) => Center(child: Text('Error loading links: $err')),
          data: (links) {
            final unconvertedLinks = links.where((link) {
              final status = link.linkStatus.trim().toLowerCase();
              final isAcceptedOrConverted = status == 'accepted' || status == 'converted';
              final isEmpId = link.employeeId.trim().toUpperCase().startsWith('EMP-');
              return !(isAcceptedOrConverted || isEmpId);
            }).toList();

            if (unconvertedLinks.isEmpty) {
              return const Center(
                child: Text(
                  'No pending candidate registration links found.',
                  style: TextStyle(color: AppColors.textSecondary),
                ),
              );
            }

            return SingleChildScrollView(
              child: SingleChildScrollView(
                scrollDirection: Axis.horizontal,
                child: DataTable(
                  headingRowHeight: 42,
                  dataRowMinHeight: 48,
                  dataRowMaxHeight: 56,
                  columns: const [
                    DataColumn(label: Text('LINK ID')),
                    DataColumn(label: Text('STATUS')),
                    DataColumn(label: Text('GENERATED BY')),
                    DataColumn(label: Text('GENERATED DATE')),
                    DataColumn(label: Text('EXPIRY DATE')),
                    DataColumn(label: Text('EMPLOYEE NAME')),
                    DataColumn(label: Text('EMPLOYEE ID')),
                    DataColumn(label: Text('ACTIONS')),
                  ],
                  rows: unconvertedLinks.map((link) {
                    final statusColor = switch (link.linkStatus) {
                      'Completed' => Colors.green,
                      'Expired' => Colors.redAccent,
                      _ => Colors.orange,
                    };

                    return DataRow(
                      cells: [
                        DataCell(
                          SelectableText(
                            link.linkId,
                            style: const TextStyle(
                              fontWeight: FontWeight.bold,
                              fontSize: 13,
                            ),
                          ),
                        ),
                        DataCell(
                          Container(
                            padding: const EdgeInsets.symmetric(
                              horizontal: 8,
                              vertical: 4,
                            ),
                            decoration: BoxDecoration(
                              color: statusColor.withValues(alpha: 0.12),
                              borderRadius: BorderRadius.circular(12),
                              border: Border.all(color: statusColor, width: 0.8),
                            ),
                            child: Text(
                              link.linkStatus,
                              style: TextStyle(
                                fontSize: 11,
                                fontWeight: FontWeight.bold,
                                color: statusColor,
                              ),
                            ),
                          ),
                        ),
                        DataCell(Text(link.generatedBy)),
                        DataCell(Text(link.generatedDate)),
                        DataCell(Text(link.expiryDate)),
                        DataCell(Text(link.employeeName.isEmpty ? '-' : link.employeeName)),
                        DataCell(Text(link.employeeId.isEmpty ? '-' : link.employeeId)),
                        DataCell(
                          Row(
                            mainAxisSize: MainAxisSize.min,
                            children: [
                              IconButton(
                                icon: const Icon(Icons.open_in_new, size: 18, color: AppColors.active),
                                tooltip: 'Open Registration Form',
                                onPressed: () {
                                  Navigator.of(context).pop();
                                  GoRouter.of(context).push('/employee/register/${link.linkId}');
                                },
                              ),
                              IconButton(
                                icon: const Icon(Icons.copy, size: 18, color: AppColors.active),
                                tooltip: 'Copy Link URL',
                                onPressed: () {
                                  Clipboard.setData(ClipboardData(text: link.fullUrl));
                                  ScaffoldMessenger.of(context).showSnackBar(
                                    const SnackBar(
                                      content: Text('Registration link copied!'),
                                      behavior: SnackBarBehavior.floating,
                                    ),
                                  );
                                },
                              ),
                            ],
                          ),
                        ),
                      ],
                    );
                  }).toList(),
                ),
              ),
            );
          },
        ),
      ),
      actions: [
        TextButton(
          onPressed: () => Navigator.of(context).pop(),
          child: const Text('Close'),
        ),
      ],
    );
  }
}
